### PR TITLE
Motd to greeting

### PR DESCRIPTION
**Pull request by msdobrescu**
motd breaks Gnome greeting display, so keep the feature as a greeting instead, should have the same effect except for Gnome greeting. If accepted, could/should be propagated in mocaccino-funtoo and other similar projects.
Two topics are opened for the same issue:
mocaccinoOS/mocaccino#11
mocaccinoOS/desktop#125
My issue opened on GDM side: https://gitlab.gnome.org/GNOME/gdm/-/issues/718

### CODE REVIEW

**Review by mudler — APPROVED** [review]
I'm still thorn by the fact that this will be still an issue if an user touches his motd, but I'm fine with this change, thanks!

**Review by mudler — CHANGES_REQUESTED** [review]
Right, the package version needs to be bumped, otherwise there is no new version to be installed 🙂

**Comment by msdobrescu** [comment]
@mudler, on one hand, anybody could setup his system to whatever he needs, mOS offers just a default setup.
On other hand, there is little work to do more on this.
What about [this](https://github.com/mocaccinoOS/os-commons/blob/65c0d43561943b75bf648e6676cb8bf105ad8342/packages/mocaccino/mocaccino-skel/mocaccino-init-skel.sh#L41) one?

**Comment by mudler** [comment]
I'm fine with this change, just needs the package version to be bumped.. we can always document this in our docs :)

**Comment by mudler** [comment]
Perfect! Thanks

**Comment by msdobrescu** [comment]
Thank _you_!

**Pull request merged**
